swagger: '2.0'
info:
  version: 1.0.0
  title: REST API
  description: ''
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /:
    get:
      description: ''
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              contact:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/contactos/:
    get:
      description: ''
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              contact:
                example: any
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /api/usuarios/login:
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              email:
                example: any
              password:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /login:
    post:
      description: ''
      parameters:
        - name: body
          in: body
          schema:
            type: object
            properties:
              email:
                example: any
              password:
                example: any
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
